Add a yaml() builtin like the python one
thought-machine/please pull request #3308
Opened 2024-11-29 14:01 UTC by Tatskaari

Converts a asp object to a yaml string.

2024-11-29 14:29 UTC, zgeor approved these changes
Thanks! Exactly what I needed

2024-11-29 14:53 UTC, peterebden approved these changes

2024-11-29 14:53 UTC, peterebden commented on rules/builtins.build_defs
> +    pass
nit: `pass` is unnecessary

2024-11-29 14:53 UTC, peterebden commented on src/parse/asp/objects.go
> +func (b pyBool) MarshalYAML() (interface{}, error) {
should this be part of the pyObject interface? I think MarshalJSON is

2024-12-03 10:44 UTC, peterebden requested changes
Thinking further about this, I'm not sure this is really necessary. As someone pointed out internally, JSON is a subset of YAML, so emitting it via the `json()` builtin would also be valid YAML for anything that wanted to consume that.

2025-01-16 18:10 UTC, closed without merging